variable "VPC_PRIVATE_CIDR"         {}
variable "VPC_PUBLIC_CIDR"          {}
variable "ENV"                      {}
variable "PRIVATE_SUBNET_CIDRS"     {}
variable "PUBLIC_SUBNET_CIDRS"      {}
variable "DEFAULT_VPC_ID"           {}
variable "DEFAULT_VPC_CIDR"         {}
variable "INTERNAL_DNS_ZONE_ID"     {}
variable "SUBNETS_AZ"               {}