variable "ENV"                      {}
variable "INSTANCE_TYPE"            {}
variable "SPOT_INSTANCE_COUNT"      {}
variable "OD_INSTANCE_COUNT"        {}
variable "COMPONENT"                {}
variable "APP_PORT"                 {}
variable "LB_RULE_PRIORITY"         {}
variable "BACKEND"                  {}
variable "APP_VERSION"              {}
